spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${rds.hostname}/${rds.db_name}?stringtype=unspecified
    username: ${rds.username}
    password: ${rds.password}
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  sql:
    init:
      mode: always
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  connection:
    url: jdbc:postgresql://${rds.hostname}/${rds.db_name}?stringtype=unspecified
rds:
  hostname: postgres:5432
  username: postgres
  password: letmein
  db_name: debit_credit

log:
  requests: true