spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${rds.hostname}/${rds.db_name}?stringtype=unspecified
    username: ${rds.username}
    password: ${rds.password}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rds:
  hostname: localhost:5432
  username: postgres
  password: letmein
  db_name: debit_credit

#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
