spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${rds.hostname}/${rds.db_name}?stringtype=unspecified
    username: ${rds.username}
    password: ${rds.password}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true

rds:
  hostname: localhost:5432
  username: postgres
  password: letmein
  db_name: debit_credit

log:
  requests: true